name: Build Source Docs

on:
  push:
   branches: [ source-docs ]
  pull_request:
    branches: [ source-docs ]

jobs:
  build-source-docs:
    runs-on: ubuntu-latest  
    name: Build Source Documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Doxygen docs
        run: |
          sudo apt-get install doxygen
          sudo apt-get install graphviz
          cd Source/docs
          doxygen Doxyfile.in
          
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Source/docs/_build/html
    
#       - name: Deploy to Netlify
#         uses: nwtgck/actions-netlify@v1.2
#         with:
#           publish-dir: 'Source/docs_sphinx/_build/html'
#           production-deploy: true
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           deploy-message: "Deploy from GitHub Actions"
#           enable-pull-request-comment: false
#           enable-commit-comment: true
#           overwrites-pull-request-comment: true
#         env:
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#         timeout-minutes: 3
